name: Run RDP Script

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        run: |
          git clone https://github.com/epic-miner/RDP.git
          cd RDP
          ls -la

      - name: Give permission & run script
        run: |
          cd RDP
          chmod +x aman.sh
          bash aman.sh
